/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.60.0
  Forc version: 0.44.0
  Fuel-Core version: 0.20.5
*/

import type {
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

export type SimplePredicateAbiConfigurables = {
  SENDER: string;
  RECIPIENT: string;
};

interface SimplePredicateAbiInterface extends Interface {
  functions: {
    main: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'main', values: []): Uint8Array;

  decodeFunctionData(functionFragment: 'main', data: BytesLike): DecodedValue;
}

export class SimplePredicateAbi extends Contract {
  interface: SimplePredicateAbiInterface;
  functions: {
    main: InvokeFunction<[], boolean>;
  };
}
